# Generated by Django 5.1.1 on 2024-09-29 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadmusApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-createdAt'],
            },
        ),
    ]
